// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: UserService.proto

package proto

import (
	common "auth-haven/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePersonalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonalUserRequest) Reset() {
	*x = CreatePersonalUserRequest{}
	mi := &file_UserService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonalUserRequest) ProtoMessage() {}

func (x *CreatePersonalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonalUserRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonalUserRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePersonalUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreatePersonalUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreatePersonalUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type CreateCompanyAndOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyName   string                 `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CompanyDomain string                 `protobuf:"bytes,2,opt,name=company_domain,json=companyDomain,proto3" json:"company_domain,omitempty"`
	OwnerEmail    string                 `protobuf:"bytes,3,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	OwnerPassword string                 `protobuf:"bytes,4,opt,name=owner_password,json=ownerPassword,proto3" json:"owner_password,omitempty"`
	OwnerFullName string                 `protobuf:"bytes,5,opt,name=owner_full_name,json=ownerFullName,proto3" json:"owner_full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyAndOwnerRequest) Reset() {
	*x = CreateCompanyAndOwnerRequest{}
	mi := &file_UserService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyAndOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyAndOwnerRequest) ProtoMessage() {}

func (x *CreateCompanyAndOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UserService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyAndOwnerRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyAndOwnerRequest) Descriptor() ([]byte, []int) {
	return file_UserService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCompanyAndOwnerRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CreateCompanyAndOwnerRequest) GetCompanyDomain() string {
	if x != nil {
		return x.CompanyDomain
	}
	return ""
}

func (x *CreateCompanyAndOwnerRequest) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *CreateCompanyAndOwnerRequest) GetOwnerPassword() string {
	if x != nil {
		return x.OwnerPassword
	}
	return ""
}

func (x *CreateCompanyAndOwnerRequest) GetOwnerFullName() string {
	if x != nil {
		return x.OwnerFullName
	}
	return ""
}

var File_UserService_proto protoreflect.FileDescriptor

const file_UserService_proto_rawDesc = "" +
	"\n" +
	"\x11UserService.proto\x12\x04auth\x1a\x13common/Tokens.proto\"j\n" +
	"\x19CreatePersonalUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"\xd8\x01\n" +
	"\x1cCreateCompanyAndOwnerRequest\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12%\n" +
	"\x0ecompany_domain\x18\x02 \x01(\tR\rcompanyDomain\x12\x1f\n" +
	"\vowner_email\x18\x03 \x01(\tR\n" +
	"ownerEmail\x12%\n" +
	"\x0eowner_password\x18\x04 \x01(\tR\rownerPassword\x12&\n" +
	"\x0fowner_full_name\x18\x05 \x01(\tR\rownerFullName2\x9d\x01\n" +
	"\vUserService\x12C\n" +
	"\x12CreatePersonalUser\x12\x1f.auth.CreatePersonalUserRequest\x1a\f.auth.Tokens\x12I\n" +
	"\x15CreateCompanyAndOwner\x12\".auth.CreateCompanyAndOwnerRequest\x1a\f.auth.TokensB\x16Z\x14auth-haven/pkg/protob\x06proto3"

var (
	file_UserService_proto_rawDescOnce sync.Once
	file_UserService_proto_rawDescData []byte
)

func file_UserService_proto_rawDescGZIP() []byte {
	file_UserService_proto_rawDescOnce.Do(func() {
		file_UserService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UserService_proto_rawDesc), len(file_UserService_proto_rawDesc)))
	})
	return file_UserService_proto_rawDescData
}

var file_UserService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_UserService_proto_goTypes = []any{
	(*CreatePersonalUserRequest)(nil),    // 0: auth.CreatePersonalUserRequest
	(*CreateCompanyAndOwnerRequest)(nil), // 1: auth.CreateCompanyAndOwnerRequest
	(*common.Tokens)(nil),                // 2: auth.Tokens
}
var file_UserService_proto_depIdxs = []int32{
	0, // 0: auth.UserService.CreatePersonalUser:input_type -> auth.CreatePersonalUserRequest
	1, // 1: auth.UserService.CreateCompanyAndOwner:input_type -> auth.CreateCompanyAndOwnerRequest
	2, // 2: auth.UserService.CreatePersonalUser:output_type -> auth.Tokens
	2, // 3: auth.UserService.CreateCompanyAndOwner:output_type -> auth.Tokens
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_UserService_proto_init() }
func file_UserService_proto_init() {
	if File_UserService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UserService_proto_rawDesc), len(file_UserService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_UserService_proto_goTypes,
		DependencyIndexes: file_UserService_proto_depIdxs,
		MessageInfos:      file_UserService_proto_msgTypes,
	}.Build()
	File_UserService_proto = out.File
	file_UserService_proto_goTypes = nil
	file_UserService_proto_depIdxs = nil
}
